name: Pull Request Stats

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          period: 30
          charts: true
          disable-links: true
          sort-by: 'COMMENTS'
